version: '3'
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - var_influxdb
      # - ./influxdb/data:/var/lib/influxdb
      # - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
    networks:
      - infra-network

  telegraf:
    container_name: telegraf
    image: telegraf
    environment:
      HOSTNAME: "telegraf-getting-started"
    networks:
      - infra-network
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  kapacitor:
    container_name: kapacitor
    image: kapacitor
    volumes:
      - var_kapacitor
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    networks:
      - infra-network
    ports:
      - "9092:9092"

  chronograf:
    container_name: chronograf
    image: loudml/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      # LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092
      # RESOURCES_PATH: "/usr/share/chronograf/resources"

      PUBLIC_URL : "http://localhost:8088"
      TOKEN_SECRET : "Super5uperUdn3verGu355!"

      # GOOGLE_CLIENT_ID : "831405758394-hd2ji8h8a196tf0fi0g1c7urjsbb2sr7.apps.googleusercontent.com"
      # GOOGLE_CLIENT_SECRET : "vWlEzeYpN_3FEe9ChuUCzwhr"

      AUTH0_DOMAIN  : "https://hls.au.auth0.com"
      AUTH0_CLIENT_ID : "mJpnXc0dXR9GZhas7QdhOZnLuZJekKoG"
      AUTH0_CLIENT_SECRET : "OjLOKt3uz61_ekShAXEcwlPti96-a14mS4pYle9Of5YQKDtn--QcWwLjcXs6nd9D"

      # GENERIC_CLIENT_ID: "chronograf"
      # GENERIC_CLIENT_SECRET: "IEvgIBADANLgkqhkiG9w0BAQEFAASCB"
      # GENERIC_AUTH_URL: "http://localhost:53414/connect/authorize"
      # GENERIC_TOKEN_URL: "http://localhost:53414/connect/token"
      # USE_ID_TOKEN: "true"
      # JWKS_URL: "http://localhost:53414/.well-known/openid-configuration"
      # GENERIC_API_URL: "http://localhost:53414/connect/userinfo"
      # GENERIC_API_KEY: "upn"
      # GENERIC_SCOPES: "openid"

    # environment:
    #   INFLUXDB_URL: http://influxdb:8086
    #   LOUDML_URL: http://loudml:8077
    #   KAPACITOR_URL: http://kapacitor:9092
    volumes:
      # - var_chronograf
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    # links:
    #   # Chronograf requires network access to InfluxDB and Kapacitor
    #   - influxdb
    #   - kapacitor
    networks:
      - infra-network
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8088:8888"
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
      # - loudml

volumes:
  var_chronograf:
  var_kapacitor:
  var_influxdb:

networks:
  infra-network:
    external: true